
JOURNAL_EVENTS = {"MDl": "Spy ran out of time.",
"MWw": "Missions completed successfully.",
"MWc": "Missions completed. %.0f second countdown.",
"MWp": "Missions completed. Countdown pending.",
"SnS": "Sniper shot Spy.",
"Sns": "Sniper shot civilian.",
"Snl": "Sniper shot too late for sync.",
"New": "Game started.",
"OT ": "Overtime!",
"ChT": "%.0f seconds added to match.",
"Cht": "%.0f seconds subtracted from match.",
"Rst": "Missions reset.",
"BTt": "Transferred microfilm.",
"BAb": "Bugged Ambassador in conversation.",
"BAB": "Bugged Ambassador while walking.",
"DAc": "Double Agent contacted.",
"SSS": "Statue swapped.",
"STS": "Target seduced.",
"ISI": "All statues inspected.",
"GLP": "Guest List purloined.",
"GLR": "Guest List returned.",
"FAF": "Fingerprinted Ambassador.",
"ChW": "Watch checked to add time.",
"ChC": "Aborted watch check to add time.",
"DAC": "Fake Banana Bread uttered.",
"DAu": "Banana Bread uttered.",
"DAx": "Banana Bread aborted.",
"DAX": "Left alone while attempting Banana Bread.",
"BTH": "Hide microfilm in book.",
"BTh": "Remove microfilm from book.",
"STf": "Flirt with seduction target: %d%%",
"STn": "Failed flirt with seduction target.",
"ISi": "Held statue inspected.",
"ISr": "Right statue inspected.",
"ISl": "Left statue inspected.",
"ISc": "Inspection interrupted.",
"SSd": "Dropped statue.",
"GLx": "Purloin Guest List aborted.",
"GLX": "Return Guest List aborted.",
"GLd": "Delegating Purloin Guest List.",
"GLt": "Delegated Purloin timer expired.",
"GLD": "Delegated Purloin to %s.",
"FAf": "Fingerprinted %s.",
"ATb": "Action test red: %s",
"ATn": "Action test white: %s",
"ATg": "Action test green: %s",
"ATi": "Action test ignored: %s",
"ATc": "Action test canceled: %s",
"DRs": "Sipped drink.",
"DRC": "Gulped drink.",
"DRS": "Took last sip of drink.",
"DRg": "Got drink from waiter.",
"DRr": "Rejected drink from waiter.",
"DRR": "Request drink from waiter.",
"DRo": "Waiter offered drink.",
"DRX": "Waiter stopped offering drink.",
"DRG": "Waiter gave up.",
"DBg": "Got drink from bartender.",
"DBr": "Rejected drink from bartender.",
"DBR": "Request drink from bartender.",
"DBD": "Demand drink from bartender.",
"DBo": "Bartender offered drink.",
"DBX": "Bartender stopped offering drink.",
"DBG": "Bartender gave up.",
"DBx": "Gave up on bartender.",
"DBc": "Bartender picked next customer.",
"DAt": "Stopped talking.",
"DAT": "Started talking.",
"DAI": "Interrupted speaker.",
"DAj": "Double Agent left conversation with Spy.",
"DAJ": "Double Agent joined conversation with Spy.",
"DAk": "Spy left conversation with Double Agent.",
"DAK": "Spy joined conversation with Double Agent.",
"Chw": "Watch checked.",
"SSg": "Picked up statue.",
"SSP": "Statue swap pending.",
"SSp": "Put back statue.",
"SSc": "Character picked up pending statue.",
"SSC": "Cast member picked up pending statue.",
"GLp": "Guest List purloin pending.",
"GLr": "Guest List return pending.",
"BTr": "Read book.",
"BTg": "Get book from bookcase.",
"BTp": "Put book in bookcase.",
"BAp": "Begin planting bug in conversation.",
"BAP": "Begin planting bug while walking.",
"BAL": "Ambassador's personal space violated.",
"DAr": "Real Banana Bread started.",
"DAf": "Fake Banana Bread started.",
"STb": "Begin flirtation with seduction target.",
"STr": "Flirtation cooldown expired.",
"STC": "Seduction canceled.",
"Sai": "Spy player takes control from AI.",
"SAI": "AI takes over Spy character.",
"Cnv": "Spy enters conversation.",
"CnV": "Spy leaves conversation.",
"Lwn": "Spy looks out window.",
"Lpn": "Spy looks at painting.",
"Brp": "Spy picks up briefcase.",
"BrP": "Spy puts down briefcase.",
"Brr": "Spy returns briefcase.",
"FAg": "Picked up fingerprintable %s.",
"FAG": "Picked up fingerprintable %s (difficult).",
"FAb": "Started fingerprinting %s.",
"FAc": "Fingerprinting canceled.",
"FAx": "Fingerprinting failed.",
"BAc": "Ambassador cast.",
"BAC": "Ambassador cast.", #manually
"DAp": "Double Agent cast.",
"DAQ": "Double Agent cast.", #manually
"DAP": "Suspected Double Agent cast.",
"STc": "Seduction Target cast.",
"STQ": "Seduction Target cast.", #manually
"SPc": "Spy cast.",
"SPC": "Spy cast.",  #manually
"Snp": "Took shot.",
"MkH": "Marked %smost suspicious.",
"Mkh": "Marked %ssuspicious.",
"Mkn": "Marked %sneutral suspicion.",
"Mkl": "Marked %sless suspicious.",
"MkL": "Marked %sleast suspicious.",
"Mkb": "Marked book.",
"LZR": "Laser event."}